create database p_3;
use p_3;
create table company(company varchar(20),amount int);
insert into company values('wipro',5000);
insert into company values('ibm',8000);
insert into company values('dell',9000);
insert into company values('wipro',2000);
insert into company values('dell',10000);
select * from company;
Select AVG (amount) from company;
Select SUM(amount) from company;
Select Max(amount) from company;
Select Min(amount) from company;
Select Count(*) from company;
select company, sum(amount) from company group by company;
select company,min(amount) from company group by company;
select company,max(amount) from company group by company;
select company,count(*) from company group by company;
select company,count() from company group by company having count()>1;
select company, sum(amount) from company group by company having sum(amount)>10000;